export const variantClasses = {
  h0: 'prose-h0 md:prose-h0-md',
  h1: 'prose-h1 md:prose-h1-md',
  h2: 'prose-h2 md:prose-h2-md',
  h3: 'prose-h3 md:prose-h3-md',
  h4: 'prose-h4 md:prose-h4-md',
  h5: 'prose-h5',
  h6: 'prose-h6',
  titleXXXXL: 'prose-titleXXXXL',
  titleXXXL: 'prose-titleXXXL',
  titleXXL: 'prose-titleXXL',
  titleXL: 'prose-titleXL md:prose-titleXL-md',
  titleLG: 'prose-titleLG',
  titleMD: 'prose-titleMD',
  titleSM: 'prose-titleSM',
  titleXS: 'prose-titleXS',
  bodyXL: 'prose-bodyXL',
  bodyLG: 'prose-bodyLG',
  bodyMD: 'prose-bodyMD',
  bodySM: 'prose-bodySM',
  bodyXS: 'prose-bodyXS',
  labelMD: 'prose-labelMD',
  labelSM: 'prose-labelSM',
  labelXS: 'prose-labelXS',
};

export const alignClasses = {
  left: 'text-left',
  center: 'text-center',
  right: 'text-right',
  top: 'align-text-top',
  bottom: 'align-text-bottom',
};
